---
- hosts: localhost
  tasks:
  
    - name: Install python3-apt
      apt:
        name: python3-apt
        update_cache: yes

    - name: Install software prop
      apt:
        name: software-properties-common
        update_cache: yes

#Debian Buster, dépôt principal + paquets non libres

    - ansible.builtin.apt_repository:
        repo: deb-src http://deb.debian.org/debian/ buster main contrib non-free
        update_cache: yes

    - ansible.builtin.apt_repository:
        repo: deb http://deb.debian.org/debian/ buster main contrib non-free
        update_cache: yes

# Debian Buster, mises à jour de sécurité + paquets non libres

    - ansible.builtin.apt_repository:
        repo: deb http://deb.debian.org/debian-security/ buster/updates main contrib non-free
        update_cache: yes

    - ansible.builtin.apt_repository:
        repo: deb-src http://deb.debian.org/debian-security/ buster/updates main contrib non-free
        update_cache: yes

# Debian Buster, mises à jour "volatiles" + paquets non libres

    - ansible.builtin.apt_repository:
        repo: deb http://deb.debian.org/debian/ buster-updates main contrib non-free
        update_cache: yes

    - ansible.builtin.apt_repository:
        repo: deb-src http://deb.debian.org/debian/ buster-updates main contrib non-free
        update_cache: yes
  
